name: Lint and Test

on: [push, pull_request, pull_request_review]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest dvc
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA3NAWU3WKN54H3PNZ
        aws-secret-access-key: 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
    
    - name: Set up DVC
      run: |
        dvc init
    
    - name: Pull data
      uses: iterative/setup-dvc@v1
      with:
        cmd: pull
        remote: s3://project3-nd0821
